baseURL = 'https://hugo.prevhelp.de'
languageCode = 'de'
title = 'PrevHelp'
disableKinds = ["taxonomy","taxonomyTerm"]

enableGitInfo = true
enableRobotsTXT = true

defaultContentLanguage = 'de'

[minify.tdewolff.html]
  keepWhitespace = false

[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']

[languages]
  [languages.de]
    baseURL = 'https://hugo.prevhelp.de'
    languageName = 'Deutsch'
    title = 'PrevHelp - Pr√§vention ist die beste Hilfe'
    weight = 1
    contentDir = 'content/de'
  [languages.en]
    baseURL = 'https://hugo.prevhelp.com'
    languageName = 'English'
    title = 'PrevHelp - Prevention is the best help'
    weight = 2
    contentDir = 'content/en'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
